2018-11-16 14:05:17,202 - alarm_data_regular_filter.py - [line:264] - ERROR - index 0 is out of bounds for axis 0 with size 0
2018-11-16 14:05:17,203 - alarm_data_regular_filter.py - [line:264] - ERROR - index 0 is out of bounds for axis 0 with size 0
2018-11-19 08:08:19,625 - alarm_data_regular_filter.py - [line:264] - ERROR - connection already closed
2018-11-19 08:08:37,525 - alarm_data_regular_filter.py - [line:264] - ERROR - connection already closed
2018-11-19 08:23:18,955 - alarm_data_regular_filter.py - [line:264] - ERROR - index 0 is out of bounds for axis 0 with size 0
2018-12-06 10:03:43,376 - SituationOperate.py - [line:236] - ERROR - so_run
2018-12-06 10:04:43,300 - SituationOperate.py - [line:236] - ERROR - so_run
2018-12-06 10:05:43,326 - SituationOperate.py - [line:236] - ERROR - so_run
2018-12-06 10:19:14,803 - SituationOperate.py - [line:236] - ERROR - so_run
2018-12-06 10:20:14,706 - SituationOperate.py - [line:236] - ERROR - so_run
2018-12-06 10:23:16,719 - SituationOperate.py - [line:236] - ERROR - so_run
2018-12-06 10:24:16,721 - SituationOperate.py - [line:236] - ERROR - so_run
2018-12-06 10:27:16,723 - SituationOperate.py - [line:236] - ERROR - so_run
2018-12-06 10:29:16,718 - SituationOperate.py - [line:236] - ERROR - so_run
2018-12-06 10:30:16,737 - SituationOperate.py - [line:236] - ERROR - so_run
2018-12-06 10:33:16,800 - SituationOperate.py - [line:236] - ERROR - so_run
2018-12-06 10:34:16,908 - SituationOperate.py - [line:236] - ERROR - so_run
2018-12-06 10:36:16,722 - SituationOperate.py - [line:236] - ERROR - so_run
2018-12-06 10:37:16,721 - SituationOperate.py - [line:236] - ERROR - so_run
2018-12-06 10:43:16,736 - SituationOperate.py - [line:236] - ERROR - so_run
2018-12-06 10:44:16,725 - SituationOperate.py - [line:236] - ERROR - so_run
